[package]
name = "flatbuffers-reflection"
version = "0.1.0"
edition = "2021"

[dependencies]
flatbuffers = { path = "../flatbuffers"}
escape_string = "0.1.2"
num-traits = "0.2.19"
anyhow = "1.0.75"
thiserror = "1.0"
